/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './message-input.component.ngfactory';
import * as i2 from './message-input.component';
import * as i3 from './message.service';
import * as i4 from './message-list.component.ngfactory';
import * as i5 from './message-list.component';
import * as i6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MessagesComponent,data:{}});
export function View_MessagesComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),4,'div',[['class','row']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-message-input',([] as any[]),
          (null as any),(null as any),(null as any),i1.View_MessageInputComponent_0,
          i1.RenderType_MessageInputComponent)),i0.ɵdid(114688,(null as any),0,i2.MessageInputComponent,
          [i3.MessageService],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),
          i0.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),
              (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
          'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),
          (null as any),i4.View_MessageListComponent_0,i4.RenderType_MessageListComponent)),
      i0.ɵdid(114688,(null as any),0,i5.MessageListComponent,[i3.MessageService],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),
          ['\n    ']))],(_ck,_v) => {
    _ck(_v,4,0);
    _ck(_v,12,0);
  },(null as any));
}
export function View_MessagesComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-messages',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,
      RenderType_MessagesComponent)),i0.ɵdid(49152,(null as any),0,i6.MessagesComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const MessagesComponentNgFactory:i0.ComponentFactory<i6.MessagesComponent> = i0.ɵccf('app-messages',
    i6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvWU0vYW5ndWxhcjRub2RlanNfbWVhbi9zZWVkLXByb2plY3QtcmV2aXNlZC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9ZTS9hbmd1bGFyNG5vZGVqc19tZWFuL3NlZWQtcHJvamVjdC1yZXZpc2VkL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvWU0vYW5ndWxhcjRub2RlanNfbWVhbi9zZWVkLXByb2plY3QtcmV2aXNlZC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvWU0vYW5ndWxhcjRub2RlanNfbWVhbi9zZWVkLXByb2plY3QtcmV2aXNlZC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICAgICAgICA8YXBwLW1lc3NhZ2UtaW5wdXQ+PC9hcHAtbWVzc2FnZS1pbnB1dD5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxocj5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgICAgICAgPGFwcC1tZXNzYWdlLWxpc3Q+PC9hcHAtbWVzc2FnZS1saXN0PlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8YXBwLW1lc3NhZ2VzPjwvYXBwLW1lc3NhZ2VzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsK0NBQ1E7TUFBQTtNQUFBLDRDQUFpQjtNQUNiO1VBQUE7NkNBQUEsVUFBQTtVQUFBLGlEQUF1QztVQUFBLGlCQUNyQywrQ0FDTjtpQkFBQTtjQUFBLDBEQUFJO1VBQUEsaUJBQ0o7VUFBQTtNQUFpQixtREFDYjtVQUFBO1VBQUE7YUFBQTtVQUFBLGVBQXFDLCtDQUNuQztVQUFBO0lBTEY7SUFJQTs7OztvQkNOWjtNQUFBO2tDQUFBLFVBQUE7TUFBQTs7OyJ9
